# description
name: "linkter"
description: "Grouped links filterer."
keywords: "angular filter"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://linkter.smutnyleszek.com"
rootSiteUrl: "http://smutnyleszek.com"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: false
timezone: Europe/Warsaw
port: 2038

# excludes
exclude:
  # disabled src, as it breaks --watch (see includes_dir below)
  # - src
  - test
  - node_modules
  - LICENSE
  - README.md
  - package.json

# pull includes from other directory
includes_dir: src
